export const FETCH_PLANTS_START = 'FETCH_PLANTS_START';
export const FETCH_PLANTS_SUCCESS = 'FETCH_PLANTS_SUCCESS';
export const ADD_PLANT = 'ADD_PLANT';
export const FETCH_PLANTS_ERROR = 'FETCH_PLANTS_ERROR';
export const CLEAR_PLANTS_STATE = 'CLEAR_PLANTS_STATE';
